### ISSUE TITLE
Generated actions do not respect RouteAttribute

### ISSUE THREAD

**Issue by cruising** [slovely/TypeScriptDefinitionsGenerator#9]
I have a FlightController which exposes a GetFlightDetails(string flightIdentifier) method which has this RouteAttribute: 
`[Route("api/v1/flight/{flightIdentifier}/flightdetails")]`

The generated action looks like this:
`return this.http.fetch("api/Flight/getFlightDetails?flightIdentifier=" + flightIdentifier + "", options)`

I would expect the action to look like this
`return this.http.fetch("api/v1/flight/" + flightIdentifier + "/flightdetails", options)`

I am using the Aurelia actions, configuration of which by the way would be good to have in the documentation. I'll make a pullrequest for it, if you'd like?

**Comment by slovely** [comment]
Yes, you are right, it doesn't really support much other than `api/{controller}/{action}/{id}` currently.  I suspect that checking actions with a RouteAttribute would be fairly straightforward though - can't promise when I will get to look at it though I'm afraid.

Thanks for the issue, and yes, a PR for docs would be good 👍

**Comment by slovely** [comment]
Got most of this working, just need to do a few more tests to make sure I haven't broken the existing functionality that we depend on, but should have an update on nuget tomorrow.

**Comment by slovely** [comment]
v1.0.44 pushed to nuget containing support for actions with a custom route specified with [Route].  Also added some info to the readme about Aurelia.  @cruising - if you want to add anything more, please feel free to send a PR!  And re-open the issue if you have any issues with custom routes.  Thanks for raising the issue.

**Comment by cruising** [comment]
Nice, thanks @slovely.
The generated actions are not quite there:
`return this.http.fetch("api/v1/flights/" + flightIdentifier + "/flightdetails" + "?flightIdentifier=" + flightIdentifier + "", options)` should be 
`return this.http.fetch("api/v1/flights/" + flightIdentifier + "/flightdetails", options)`

The signature on the controller looks like this

` [HttpGet]
        [Route("api/v1/flights/{flightIdentifier}/flightdetails")]
        public FlightDetails GetFlightDetails(string flightIdentifier)`

Documentation is spot on, I was mostly looking for the `TsGenApiMethodStyle` option in the props file.

**Comment by slovely** [comment]
New nuget package has been pushed... sorry, I messed up the bit that supressed route parameters from the querystring.

**Comment by cruising** [comment]
Looks perfect, thanks.
